"""
export_js.py

Exports a fitted SimplifiedBoundaryModel to a single, dependency-free
JavaScript file that runs entirely client-side in a browser -- no server,
no Python, no ML library. This is the direct payoff of folding the whole
surrogate into a handful of NumPy arrays: those arrays (and the small
amount of math that combines them) translate one-for-one into vanilla JS.

What gets exported, per basis:
  - "poly2": mean, P (PCA projection), a, W, c  -> score = c + z.a + z^T W z
  - "polyN": mean, P, idx, coef, c              -> score = c + sum coef_m * monomial_m(z)
  - "rbf":   mean, P, Omega, b, w, c, scale      -> score = c + sum w_i cos(omega_i.z + b_i)

Optionally also exports a scikit-learn TfidfVectorizer's vocabulary + IDF
weights, so raw text can be vectorized client-side too (see
`export_tfidf_vectorizer`) -- the JS tokenizer matches sklearn's default
token pattern (`\\b\\w\\w+\\b`, lowercased) and default L2 normalization,
so vectors match sklearn's own `.transform()` output on the same text
(verified numerically against Node.js in this project's test run).

Usage:
    from export_js import export_model_to_js
    export_model_to_js(simplified_model, "classifier.js", vectorizer=vec)
"""

import json
import numpy as np


def _arr(a):
    """NumPy array -> nested Python list, JSON-safe."""
    return None if a is None else np.asarray(a).tolist()


def _model_to_params_dict(model):
    d = {"basis": model.basis, "n_components": model.n_components,
         "mean": _arr(model.mean), "P": _arr(model.P)}
    p = model.params
    if model.basis == "poly2":
        d["a"] = _arr(p["a"]); d["W"] = _arr(p["W"]); d["c"] = p["c"]
    elif model.basis == "polyN":
        d["idx"] = _arr(p["idx"]); d["coef"] = _arr(p["coef"]); d["c"] = p["c"]
    elif model.basis == "rbf":
        d["Omega"] = _arr(p["Omega"]); d["b"] = _arr(p["b"])
        d["w"] = _arr(p["w"]); d["c"] = p["c"]; d["scale"] = p["scale"]
    return d


def _vectorizer_to_params_dict(vectorizer):
    """Extracts what's needed to reproduce TfidfVectorizer(stop_words='english')
    .transform() in JS: vocabulary (word -> column index), per-feature IDF
    weights, and whether L2 normalization is applied (sklearn default)."""
    return {
        "vocabulary": {word: int(idx) for word, idx in vectorizer.vocabulary_.items()},
        "idf": vectorizer.idf_.tolist(),
        "lowercase": bool(vectorizer.lowercase),
        "norm": vectorizer.norm or None,
    }


_JS_TEMPLATE = r"""// Auto-generated by export_js.py -- a self-contained, dependency-free
// JavaScript port of a Python closed-form decision-boundary surrogate.
// No build step, no imports: load this file with a standard script tag
// and use the global BoundaryClassifier class it defines below.
// (Note for anyone editing this template: never put the closing script
// tag's character sequence inside this file as literal text, even inside
// a JS comment or string -- the HTML parser ends the enclosing script
// element the instant it sees that sequence, comment or not, which
// silently truncates the real code that follows it.)

const MODEL_PARAMS = __MODEL_JSON__;
const VECTORIZER_PARAMS = __VECTORIZER_JSON__;  // null if not exported

function _sigmoid(x) { return 1 / (1 + Math.exp(-x)); }

function _matVec(M, v) {
  // M: (rows x cols) nested array, v: (cols) array -> (rows) array
  const out = new Array(M.length);
  for (let i = 0; i < M.length; i++) {
    let s = 0;
    const row = M[i];
    for (let j = 0; j < row.length; j++) s += row[j] * v[j];
    out[i] = s;
  }
  return out;
}

class BoundaryClassifier {
  constructor(params) { this.p = params; }

  // x: plain array of raw feature values (already vectorized, same
  // dimensionality the Python model was trained on).
  _project(x) {
    if (!this.p.P) return x;  // skip_pca case: input IS the reduced space
    const d = this.p.P.length, k = this.p.P[0].length;
    const centered = new Array(d);
    for (let i = 0; i < d; i++) centered[i] = x[i] - this.p.mean[i];
    const z = new Array(k).fill(0);
    for (let i = 0; i < d; i++) {
      const row = this.p.P[i];
      const ci = centered[i];
      if (ci === 0) continue;
      for (let j = 0; j < k; j++) z[j] += ci * row[j];
    }
    return z;
  }

  _score(z) {
    const p = this.p;
    if (p.basis === "poly2") {
      let quad = 0;
      const Wz = _matVec(p.W, z);
      for (let i = 0; i < z.length; i++) quad += z[i] * Wz[i];
      let lin = 0;
      for (let i = 0; i < z.length; i++) lin += z[i] * p.a[i];
      return p.c + lin + quad;
    } else if (p.basis === "polyN") {
      let score = p.c;
      for (let f = 0; f < p.idx.length; f++) {
        let term = 1;
        for (const col of p.idx[f]) { if (col >= 0) term *= z[col]; }
        score += term * p.coef[f];
      }
      return score;
    } else if (p.basis === "rbf") {
      const D = p.b.length;
      let score = p.c;
      for (let j = 0; j < D; j++) {
        let dot = p.b[j];
        for (let i = 0; i < z.length; i++) dot += z[i] * p.Omega[i][j];
        score += Math.cos(dot) * p.scale * p.w[j];
      }
      return score;
    }
    throw new Error("Unknown basis: " + p.basis);
  }

  // x: array of raw feature values -> P(class=1) in [0,1]
  predictProba(x) {
    return _sigmoid(this._score(this._project(x)));
  }

  // x: array of raw feature values -> 0 or 1
  predict(x) {
    return this.predictProba(x) >= 0.5 ? 1 : 0;
  }
}

// --- Optional: client-side TF-IDF vectorizer matching sklearn's default
// TfidfVectorizer(stop_words='english').transform() on the SAME vocabulary
// this model was trained with. Only present if a vectorizer was exported.
class TfidfVectorizerJS {
  constructor(params) {
    this.vocab = params.vocabulary;
    this.idf = params.idf;
    this.lowercase = params.lowercase;
    this.norm = params.norm;
    this.dim = params.idf.length;
  }

  _tokenize(text) {
    if (this.lowercase) text = text.toLowerCase();
    // Matches sklearn's default token_pattern: r"(?u)\b\w\w+\b"
    return text.match(/[a-zA-Z0-9_]{2,}/g) || [];
  }

  transform(text) {
    const counts = new Array(this.dim).fill(0);
    for (const tok of this._tokenize(text)) {
      const idx = this.vocab[tok];
      if (idx !== undefined) counts[idx] += 1;
    }
    const tfidf = new Array(this.dim);
    for (let i = 0; i < this.dim; i++) tfidf[i] = counts[i] * this.idf[i];
    if (this.norm === "l2") {
      let normSq = 0;
      for (let i = 0; i < this.dim; i++) normSq += tfidf[i] * tfidf[i];
      const n = Math.sqrt(normSq) || 1;
      for (let i = 0; i < this.dim; i++) tfidf[i] /= n;
    }
    return tfidf;
  }
}

const classifier = new BoundaryClassifier(MODEL_PARAMS);
const vectorizer = VECTORIZER_PARAMS ? new TfidfVectorizerJS(VECTORIZER_PARAMS) : null;

// Convenience one-shot function for text: raw string in, probability out.
function classifyText(text) {
  if (!vectorizer) throw new Error("No vectorizer was exported with this model.");
  return classifier.predictProba(vectorizer.transform(text));
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { BoundaryClassifier, TfidfVectorizerJS, classifier, vectorizer, classifyText };
}
"""


_DEMO_HTML_TEMPLATE = r"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>__TITLE__</title>
<style>
  html,body{margin:0;height:100%;background:#0f1115;color:#e8e8e8;font-family:system-ui,sans-serif;}
  .wrap{max-width:640px;margin:0 auto;padding:32px 20px;}
  h1{font-size:20px;margin-bottom:4px;}
  p.sub{opacity:0.65;font-size:13px;margin-top:0;margin-bottom:24px;}
  textarea{width:100%;min-height:110px;background:#1a1d24;color:#eee;border:1px solid #333;
           border-radius:8px;padding:12px;font-size:14px;box-sizing:border-box;resize:vertical;}
  button{margin-top:12px;background:#3aa0ff;color:#fff;border:none;border-radius:8px;
         padding:10px 20px;font-size:14px;cursor:pointer;}
  button:hover{background:#2b8fe6;}
  #result{margin-top:20px;padding:16px;border-radius:8px;background:#1a1d24;display:none;}
  #result.show{display:block;}
  .bar-bg{background:#2a2e38;border-radius:6px;height:22px;overflow:hidden;margin-top:8px;}
  .bar-fill{height:100%;transition:width 0.25s ease;}
  .label-row{display:flex;justify-content:space-between;font-size:13px;margin-top:6px;opacity:0.8;}
  .verdict{font-size:17px;font-weight:600;margin-bottom:4px;}
  .note{margin-top:28px;font-size:11.5px;opacity:0.55;line-height:1.5;}
</style>
</head>
<body>
<div class="wrap">
  <h1>__TITLE__</h1>
  <p class="sub">100% client-side: no server call, no network request, no Python -- vanilla JS in this page.</p>
  <textarea id="input" placeholder="__PLACEHOLDER__"></textarea>
  <br>
  <button onclick="runClassify()">Classify</button>
  <div id="result">
    <div class="verdict" id="verdict"></div>
    <div class="bar-bg"><div class="bar-fill" id="bar"></div></div>
    <div class="label-row"><span>__CLASS0_LABEL__</span><span>__CLASS1_LABEL__</span></div>
  </div>
  <div class="note">
    Model: __MODEL_DESC__.<br>
    This entire page (classifier + text vectorizer) is __FILE_SIZE__ KB of plain JavaScript --
    open the page source to see it all; there is nothing else loading.
  </div>
</div>
<script>
__JS_BODY__

function runClassify() {
  const text = document.getElementById('input').value;
  if (!text.trim()) return;
  const proba = classifyText(text);
  const pct = Math.round(proba * 100);
  const el = document.getElementById('result');
  el.classList.add('show');
  document.getElementById('verdict').textContent =
    (proba >= 0.5 ? '__CLASS1_LABEL__' : '__CLASS0_LABEL__') + '  (' + (proba*100).toFixed(1) + '%)';
  const bar = document.getElementById('bar');
  bar.style.width = pct + '%';
  bar.style.background = proba >= 0.5 ? '#e74c3c' : '#27ae60';
}
</script>
</body>
</html>
"""


def export_demo_html(model, vectorizer, path, title, class0_label, class1_label,
                      placeholder="Type or paste text here...", model_desc=None):
    """Builds a single self-contained HTML demo page: a text box, a
    Classify button, and the exported classifier + vectorizer inlined
    directly in a <script> tag -- no external .js file, no network
    request, works by just double-clicking the file open in a browser."""
    params = _model_to_params_dict(model)
    vec_params = _vectorizer_to_params_dict(vectorizer)
    js_body = (_JS_TEMPLATE
               .replace("__MODEL_JSON__", json.dumps(params))
               .replace("__VECTORIZER_JSON__", json.dumps(vec_params)))

    desc = model_desc or (f"{model.basis} surrogate, {model.n_components} components, "
                           f"distilled from a trained neural network")
    html = (_DEMO_HTML_TEMPLATE
            .replace("__TITLE__", title)
            .replace("__PLACEHOLDER__", placeholder)
            .replace("__CLASS0_LABEL__", class0_label)
            .replace("__CLASS1_LABEL__", class1_label)
            .replace("__MODEL_DESC__", desc)
            .replace("__JS_BODY__", js_body))
    size_kb = len(html) / 1024
    html = html.replace("__FILE_SIZE__", f"{size_kb:.0f}")

    with open(path, "w") as f:
        f.write(html)
    print(f"Wrote {path} ({size_kb:.1f} KB, fully self-contained)")
    return path


def export_model_to_js(model, path, vectorizer=None):
    params = _model_to_params_dict(model)
    vec_params = _vectorizer_to_params_dict(vectorizer) if vectorizer is not None else None

    js = (_JS_TEMPLATE
          .replace("__MODEL_JSON__", json.dumps(params))
          .replace("__VECTORIZER_JSON__", json.dumps(vec_params) if vec_params else "null"))

    with open(path, "w") as f:
        f.write(js)
    size_kb = len(js) / 1024
    print(f"Wrote {path} ({size_kb:.1f} KB, basis={model.basis}, "
          f"vectorizer={'included' if vectorizer else 'not included'})")
    return path


if __name__ == "__main__":
    import subprocess
    from data_utils import load_text_classification_data
    from baseline_model import train_baseline
    from boundary_simplifier import autotune_surrogate

    X_train, X_test, y_train, y_test, vec, source = load_text_classification_data()
    baseline = train_baseline(X_train, y_train)
    simplified, report = autotune_surrogate(baseline, X_train, y_train,
                                             max_accuracy_drop=0.001, verbose=False)
    print(f"Chosen config: {report['chosen_config']}")

    js_path = "/home/claude/boundary_project/classifier_export.js"
    export_model_to_js(simplified, js_path, vectorizer=vec)

    # Cross-check: run the exported JS through Node and compare against
    # Python's own predict_proba on the same raw test points.
    X_test_dense = X_test.toarray() if hasattr(X_test, "toarray") else X_test
    py_proba = simplified.predict_proba(X_test_dense)

    node_script = f"""
    const {{ classifier }} = require('{js_path}');
    const rows = {json.dumps(X_test_dense[:15].tolist())};
    const out = rows.map(r => classifier.predictProba(r));
    console.log(JSON.stringify(out));
    """
    result = subprocess.run(["node", "-e", node_script], capture_output=True, text=True)
    if result.returncode != 0:
        print("Node error:", result.stderr)
    else:
        js_proba = json.loads(result.stdout)
        max_diff = max(abs(a - b) for a, b in zip(js_proba, py_proba[:15]))
        print(f"Cross-check vs Node.js on 15 real test points: max |Python - JS| = {max_diff:.2e}")
